hwi_oauth_redirect:
    host:     "{domain}"
    requirements:
        domain: '%domain%'
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /integration/login

hwi_oauth_connect:
    host:     "{domain}"
    requirements:
        domain: '%domain%'
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    host:     "{domain}"
    requirements:
        domain: '%domain%'
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /integration/login
    
google_login:
    host:     "{domain}"
    requirements:
        domain: '%domain%'
    path: /login/check-google    
    
twitter_login:
    host:     "{domain}"
    requirements:
        domain: '%domain%'
    path: /login/check-twitter      

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

site:
    host:     "{domain}"
    requirements:
        domain: '%domain%'
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    host:     "app.{domain}"
    requirements:
        domain: '%domain%'
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api:
    host:     "app.{domain}"
    requirements:
        domain: '%domain%'
    resource: "@AppBundle/Resources/config/api.yml"
    prefix:   /api/v1
    
admin:
    host:     "admin.{domain}"
    requirements:
        domain: '%domain%'
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /
    