accountmember_index:
    path:     /
    defaults: { _controller: "AppBundle:AccountMember:index" }
    methods:  GET

accountmember_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:AccountMember:show" }
    methods:  GET

accountmember_new:
    path:     /new
    defaults: { _controller: "AppBundle:AccountMember:new" }
    methods:  [GET, POST]

accountmember_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:AccountMember:edit" }
    methods:  [GET, POST]

accountmember_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:AccountMember:delete" }
    methods:  DELETE
