confirm_index:
    path:     /
    defaults: { _controller: "AppBundle:Confirm:index" }
    methods:  GET

confirm_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Confirm:show" }
    methods:  GET

confirm_new:
    path:     /new
    defaults: { _controller: "AppBundle:Confirm:new" }
    methods:  [GET, POST]

confirm_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Confirm:edit" }
    methods:  [GET, POST]

confirm_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Confirm:delete" }
    methods:  DELETE
