dealworkflow_index:
    path:     /
    defaults: { _controller: "AppBundle:DealWorkflow:index" }
    methods:  GET

dealworkflow_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:DealWorkflow:show" }
    methods:  GET

dealworkflow_new:
    path:     /new
    defaults: { _controller: "AppBundle:DealWorkflow:new" }
    methods:  [GET, POST]

dealworkflow_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:DealWorkflow:edit" }
    methods:  [GET, POST]

dealworkflow_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:DealWorkflow:delete" }
    methods:  DELETE
