deal_index:
    path:     /
    defaults: { _controller: "AppBundle:Deal:index" }
    methods:  GET

deal_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Deal:show" }
    methods:  GET

deal_new:
    path:     /new
    defaults: { _controller: "AppBundle:Deal:new" }
    methods:  [GET, POST]

deal_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Deal:edit" }
    methods:  [GET, POST]

deal_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Deal:delete" }
    methods:  DELETE
    
#----

api_deal_show:
    path:     /{id}
    defaults: { _controller: "AppBundle:API/Deal:show" }
    methods:  [GET, PUT]
    
    
api_deal_company:
    path:     /{id}/companies
    defaults: { _controller: "AppBundle:API/Deal:companies" }
    methods:  [GET, POST]    
    
api_deal_client_tasks:
    path:     /{id}/clients/{client_id}/tasks
    defaults: { _controller: "AppBundle:API/Deal:tasks" }
    methods:  [POST]    
    
api_deal_client_notes:
    path:     /{id}/clients/{client_id}/notes
    defaults: { _controller: "AppBundle:API/Deal:notes" }
    methods:  [POST]   
    
api_deal_client_mails:
    path:     /{id}/clients/{client_id}/mails
    defaults: { _controller: "AppBundle:API/Deal:mails" }
    methods:  [POST]       
    
