industry_index:
    path:     /
    defaults: { _controller: "AppBundle:API/Industry:index" }
    methods:  GET

industry_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Industry:show" }
    methods:  GET

industry_new:
    path:     /new
    defaults: { _controller: "AppBundle:Industry:new" }
    methods:  [GET, POST]

industry_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Industry:edit" }
    methods:  [GET, POST]

industry_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Industry:delete" }
    methods:  DELETE
