msg_index:
    path:     /
    defaults: { _controller: "AppBundle:Msg:index" }
    methods:  GET

msg_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Msg:show" }
    methods:  GET

msg_new:
    path:     /new
    defaults: { _controller: "AppBundle:Msg:new" }
    methods:  [GET, POST]

msg_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Msg:edit" }
    methods:  [GET, POST]

msg_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Msg:delete" }
    methods:  DELETE


    
#-------

api_msg_reply:
    path:     /{id}/reply
    defaults: { _controller: "AppBundle:API/Msg:reply" }
    methods:  [POST]
    
api_msg_forward:
    path:     /{id}/forward
    defaults: { _controller: "AppBundle:API/Msg:forward" }
    methods:  [POST]    