note_index:
    path:     /
    defaults: { _controller: "AppBundle:Note:index" }
    methods:  GET

note_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Note:show" }
    methods:  GET

note_new:
    path:     /new
    defaults: { _controller: "AppBundle:Note:new" }
    methods:  [GET, POST]

note_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Note:edit" }
    methods:  [GET, POST]

note_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Note:delete" }
    methods:  DELETE

# ---

api_note_show:
    path:     /{id}
    defaults: { _controller: "AppBundle:API/Note:show" }
    methods:  [GET, PUT, DELETE]
    