stage_index:
    path:     /
    defaults: { _controller: "AppBundle:Stage:index" }
    methods:  GET

stage_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Stage:show" }
    methods:  GET

stage_new:
    path:     /new
    defaults: { _controller: "AppBundle:Stage:new" }
    methods:  [GET, POST]

stage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Stage:edit" }
    methods:  [GET, POST]

stage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Stage:delete" }
    methods:  DELETE

#-------

api_stage_get:
    path:     /{id}
    defaults: { _controller: "AppBundle:API/Stage:show" }
    methods:  [GET, PUT, DELETE]
    
api_stage_deals:
    path:     /{id}/deals
    defaults: { _controller: "AppBundle:API/Stage:deals" }
    methods:  [GET, POST]    