token_index:
    path:     /
    defaults: { _controller: "AppBundle:Token:index" }
    methods:  GET

token_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Token:show" }
    methods:  GET

token_new:
    path:     /new
    defaults: { _controller: "AppBundle:Token:new" }
    methods:  [GET, POST]

token_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Token:edit" }
    methods:  [GET, POST]

token_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Token:delete" }
    methods:  DELETE
