upload_index:
    path:     /
    defaults: { _controller: "AppBundle:Upload:index" }
    methods:  GET

upload_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Upload:show" }
    methods:  GET

upload_new:
    path:     /new
    defaults: { _controller: "AppBundle:Upload:new" }
    methods:  [GET, POST]

upload_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Upload:edit" }
    methods:  [GET, POST]

upload_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Upload:delete" }
    methods:  DELETE
