admin_accountmember_index:
    path:     /
    defaults: { _controller: "AdminBundle:AccountMember:index" }
    methods:  GET

admin_accountmember_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:AccountMember:show" }
    methods:  GET

admin_accountmember_new:
    path:     /new
    defaults: { _controller: "AdminBundle:AccountMember:new" }
    methods:  [GET, POST]

admin_accountmember_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:AccountMember:edit" }
    methods:  [GET, POST]

admin_accountmember_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:AccountMember:delete" }
    methods:  DELETE
