admin_account_index:
    path:     /
    defaults: { _controller: "AdminBundle:Account:index" }
    methods:  GET

admin_account_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Account:show" }
    methods:  GET

admin_account_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Account:new" }
    methods:  [GET, POST]

admin_account_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Account:edit" }
    methods:  [GET, POST]

admin_account_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Account:delete" }
    methods:  DELETE
    
#------

admin_account_workspaces:
    path:     /{id}/workspaces
    defaults: { _controller: "AdminBundle:API/Account:workspace" }
    methods:  [GET, POST]    
    
admin_account_workspaces2:
    path:     /{id}/workspaces/
    defaults: { _controller: "AdminBundle:API/Account:workspace" }
    methods:  [GET, POST]      
