actiontype_index:
    path:     /
    defaults: { _controller: "AdminBundle:ActionType:index" }
    methods:  GET

actiontype_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:ActionType:show" }
    methods:  GET

actiontype_new:
    path:     /new
    defaults: { _controller: "AdminBundle:ActionType:new" }
    methods:  [GET, POST]

actiontype_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:ActionType:edit" }
    methods:  [GET, POST]

actiontype_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:ActionType:delete" }
    methods:  DELETE
