addpipe_index:
    path:     /
    defaults: { _controller: "AdminBundle:Addpipe:index" }
    methods:  GET

addpipe_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Addpipe:show" }
    methods:  GET

addpipe_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Addpipe:new" }
    methods:  [GET, POST]

addpipe_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Addpipe:edit" }
    methods:  [GET, POST]

addpipe_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Addpipe:delete" }
    methods:  DELETE
