auth_index:
    path:     /
    defaults: { _controller: "AdminBundle:Auth:index" }
    methods:  GET

auth_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Auth:show" }
    methods:  GET

auth_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Auth:new" }
    methods:  [GET, POST]

auth_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Auth:edit" }
    methods:  [GET, POST]

auth_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Auth:delete" }
    methods:  DELETE
