clienttwitter_index:
    path:     /
    defaults: { _controller: "AdminBundle:ClientTwitter:index" }
    methods:  GET

clienttwitter_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:ClientTwitter:show" }
    methods:  GET

clienttwitter_new:
    path:     /new
    defaults: { _controller: "AdminBundle:ClientTwitter:new" }
    methods:  [GET, POST]

clienttwitter_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:ClientTwitter:edit" }
    methods:  [GET, POST]

clienttwitter_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:ClientTwitter:delete" }
    methods:  DELETE
