clientlyseniority_index:
    path:     /
    defaults: { _controller: "AdminBundle:ClientlySeniority:index" }
    methods:  GET

clientlyseniority_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:ClientlySeniority:show" }
    methods:  GET

clientlyseniority_new:
    path:     /new
    defaults: { _controller: "AdminBundle:ClientlySeniority:new" }
    methods:  [GET, POST]

clientlyseniority_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:ClientlySeniority:edit" }
    methods:  [GET, POST]

clientlyseniority_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:ClientlySeniority:delete" }
    methods:  DELETE
