clientlykeywords_index:
    path:     /
    defaults: { _controller: "AdminBundle:ClientlyKeywords:index" }
    methods:  GET

clientlykeywords_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:ClientlyKeywords:show" }
    methods:  GET

clientlykeywords_new:
    path:     /new
    defaults: { _controller: "AdminBundle:ClientlyKeywords:new" }
    methods:  [GET, POST]

clientlykeywords_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:ClientlyKeywords:edit" }
    methods:  [GET, POST]

clientlykeywords_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:ClientlyKeywords:delete" }
    methods:  DELETE
