clientlyindustries_index:
    path:     /
    defaults: { _controller: "AdminBundle:ClientlyIndustries:index" }
    methods:  GET

clientlyindustries_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:ClientlyIndustries:show" }
    methods:  GET

clientlyindustries_new:
    path:     /new
    defaults: { _controller: "AdminBundle:ClientlyIndustries:new" }
    methods:  [GET, POST]

clientlyindustries_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:ClientlyIndustries:edit" }
    methods:  [GET, POST]

clientlyindustries_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:ClientlyIndustries:delete" }
    methods:  DELETE
