country_index:
    path:     /
    defaults: { _controller: "AdminBundle:Country:index" }
    methods:  GET

country_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Country:show" }
    methods:  GET

country_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Country:new" }
    methods:  [GET, POST]

country_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Country:edit" }
    methods:  [GET, POST]

country_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Country:delete" }
    methods:  DELETE
