dealstage_index:
    path:     /
    defaults: { _controller: "AdminBundle:DealStage:index" }
    methods:  GET

dealstage_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:DealStage:show" }
    methods:  GET

dealstage_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DealStage:new" }
    methods:  [GET, POST]

dealstage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DealStage:edit" }
    methods:  [GET, POST]

dealstage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DealStage:delete" }
    methods:  DELETE
