lead_index:
    path:     /
    defaults: { _controller: "AdminBundle:Lead:index" }
    methods:  GET

lead_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Lead:show" }
    methods:  GET

lead_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Lead:new" }
    methods:  [GET, POST]

lead_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Lead:edit" }
    methods:  [GET, POST]

lead_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Lead:delete" }
    methods:  DELETE
