msg_index:
    path:     /
    defaults: { _controller: "AdminBundle:Msg:index" }
    methods:  GET

msg_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Msg:show" }
    methods:  GET

msg_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Msg:new" }
    methods:  [GET, POST]

msg_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Msg:edit" }
    methods:  [GET, POST]

msg_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Msg:delete" }
    methods:  DELETE
