share_index:
    path:     /
    defaults: { _controller: "AdminBundle:Share:index" }
    methods:  GET

share_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Share:show" }
    methods:  GET

share_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Share:new" }
    methods:  [GET, POST]

share_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Share:edit" }
    methods:  [GET, POST]

share_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Share:delete" }
    methods:  DELETE
