workflowdefault_index:
    path:     /
    defaults: { _controller: "AdminBundle:WorkflowDefault:index" }
    methods:  GET

workflowdefault_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:WorkflowDefault:show" }
    methods:  GET

workflowdefault_new:
    path:     /new
    defaults: { _controller: "AdminBundle:WorkflowDefault:new" }
    methods:  [GET, POST]

workflowdefault_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:WorkflowDefault:edit" }
    methods:  [GET, POST]

workflowdefault_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:WorkflowDefault:delete" }
    methods:  DELETE
